# Generated by Django 5.1.1 on 2024-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=255)),
                ('service_city', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('service_des', models.TextField()),
            ],
        ),
    ]
