# Generated by Django 5.1.1 on 2024-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('Banquet Halls', 'Banquet Halls'), ('Wedding Resorts', 'Wedding Resorts'), ('Destination Wedding Venues', 'Destination Wedding Venues'), ('4 Star & Above Wedding Hotels', '4 Star & Above Wedding Hotels'), ('Venue Concierge services', 'Venue Concierge services'), ('Small function & Party Halls', 'Small function & Party Halls'), ('View all Venues', 'View all Venues')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
