# Generated by Django 5.1.1 on 2024-12-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_vendor_vendors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Phone',
            new_name='Password',
        ),
    ]
