# Generated by Django 5.2 on 2025-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_vendor_delete_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
